name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 runtime
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: ./mvnw --batch-mode --no-transfer-progress clean test
      - name: Build with Maven
        run: ./mvnw --batch-mode --no-transfer-progress package -DskipTests
